BEGIN;

-- Extensión utilizada para generar y verificar hashes seguros de contraseñas.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- Función común para mantener updated_at automáticamente
-- ============================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

-- ============================================================
-- Usuarios administradores
-- ============================================================

CREATE TABLE admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password_hash TEXT NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_admin_users_username UNIQUE (username),
    CONSTRAINT ck_admin_users_username_not_blank
        CHECK (BTRIM(username) <> ''),
    CONSTRAINT ck_admin_users_full_name_not_blank
        CHECK (BTRIM(full_name) <> ''),
    CONSTRAINT ck_admin_users_password_hash_not_blank
        CHECK (BTRIM(password_hash) <> '')
);

CREATE INDEX idx_admin_users_active
    ON admin_users (is_active);

CREATE TRIGGER trg_admin_users_updated_at
BEFORE UPDATE ON admin_users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE admin_users IS
'Usuarios autorizados para acceder al panel administrativo.';

-- ============================================================
-- Categorías
-- ============================================================

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_categories_name UNIQUE (name),
    CONSTRAINT ck_categories_name_not_blank
        CHECK (BTRIM(name) <> '')
);

CREATE INDEX idx_categories_active
    ON categories (is_active);

CREATE TRIGGER trg_categories_updated_at
BEFORE UPDATE ON categories
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE categories IS
'Categorías utilizadas para organizar las preguntas frecuentes.';

-- ============================================================
-- Preguntas
-- ============================================================

CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    question_text TEXT NOT NULL,
    normalized_text VARCHAR(500) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_questions_category
        FOREIGN KEY (category_id)
        REFERENCES categories(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_questions_normalized_text
        UNIQUE (normalized_text),

    CONSTRAINT ck_questions_question_text_not_blank
        CHECK (BTRIM(question_text) <> ''),

    CONSTRAINT ck_questions_normalized_text_not_blank
        CHECK (BTRIM(normalized_text) <> '')
);

CREATE INDEX idx_questions_category_id
    ON questions (category_id);

CREATE INDEX idx_questions_active
    ON questions (is_active);

CREATE INDEX idx_questions_category_active
    ON questions (category_id, is_active);

CREATE TRIGGER trg_questions_updated_at
BEFORE UPDATE ON questions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE questions IS
'Preguntas frecuentes administradas desde el panel web.';

COMMENT ON COLUMN questions.normalized_text IS
'Texto normalizado utilizado para buscar coincidencias de consultas.';

-- ============================================================
-- Respuestas
-- Una pregunta tendrá una respuesta asociada.
-- ============================================================

CREATE TABLE answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    answer_text TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_answers_question
        FOREIGN KEY (question_id)
        REFERENCES questions(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT uq_answers_question_id
        UNIQUE (question_id),

    CONSTRAINT ck_answers_answer_text_not_blank
        CHECK (BTRIM(answer_text) <> '')
);

CREATE INDEX idx_answers_active
    ON answers (is_active);

CREATE TRIGGER trg_answers_updated_at
BEFORE UPDATE ON answers
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE answers IS
'Respuestas asociadas a las preguntas frecuentes.';

-- ============================================================
-- Configuración del bot
-- Se utiliza un registro único identificado con id = 1.
-- El token de Telegram no se almacena en la base de datos.
-- ============================================================

CREATE TABLE bot_settings (
    id SMALLINT PRIMARY KEY DEFAULT 1,
    hospital_name VARCHAR(150) NOT NULL,
    telegram_chat_id VARCHAR(100),
    bot_username VARCHAR(100),
    welcome_message TEXT NOT NULL,
    unknown_question_message TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_bot_settings_singleton
        CHECK (id = 1),

    CONSTRAINT ck_bot_settings_hospital_name_not_blank
        CHECK (BTRIM(hospital_name) <> ''),

    CONSTRAINT ck_bot_settings_welcome_message_not_blank
        CHECK (BTRIM(welcome_message) <> ''),

    CONSTRAINT ck_bot_settings_unknown_message_not_blank
        CHECK (BTRIM(unknown_question_message) <> '')
);

CREATE TRIGGER trg_bot_settings_updated_at
BEFORE UPDATE ON bot_settings
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE bot_settings IS
'Configuración general del bot y del chat o grupo de Telegram.';

COMMENT ON COLUMN bot_settings.telegram_chat_id IS
'ID configurable del chat o grupo utilizado por Telegram.';

-- ============================================================
-- Historial de consultas
-- ============================================================

CREATE TABLE query_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_user_id BIGINT,
    telegram_username VARCHAR(150),
    telegram_first_name VARCHAR(150),
    telegram_chat_id BIGINT,
    original_query TEXT NOT NULL,
    normalized_query VARCHAR(500) NOT NULL,
    question_id BIGINT,
    category_id BIGINT,
    response_text TEXT NOT NULL,
    was_answered BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_query_logs_question
        FOREIGN KEY (question_id)
        REFERENCES questions(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_query_logs_category
        FOREIGN KEY (category_id)
        REFERENCES categories(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT ck_query_logs_original_query_not_blank
        CHECK (BTRIM(original_query) <> ''),

    CONSTRAINT ck_query_logs_normalized_query_not_blank
        CHECK (BTRIM(normalized_query) <> ''),

    CONSTRAINT ck_query_logs_response_text_not_blank
        CHECK (BTRIM(response_text) <> '')
);

CREATE INDEX idx_query_logs_created_at
    ON query_logs (created_at DESC);

CREATE INDEX idx_query_logs_was_answered
    ON query_logs (was_answered);

CREATE INDEX idx_query_logs_question_id
    ON query_logs (question_id);

CREATE INDEX idx_query_logs_category_id
    ON query_logs (category_id);

CREATE INDEX idx_query_logs_telegram_user_id
    ON query_logs (telegram_user_id);

CREATE INDEX idx_query_logs_normalized_query
    ON query_logs (normalized_query);

COMMENT ON TABLE query_logs IS
'Historial de consultas realizadas por usuarios de Telegram.';

COMMIT;
